version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    command: gunicorn hiringdog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./git-source:/app/Hiringdog-backend
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

volumes:
  postgres_data:
